// asciinema-dashboard/frontend-backup/components/Grid.vue
<script setup lang="ts">
  import Player from "./Player.vue";
  import { ref } from "vue";
  import { serverMessageSchema, type clientMessage } from "../../types";
  import { usePlayerStore } from "../store";
  const streams = ref<string[]>([]);
  const store = usePlayerStore();
  const ws = new WebSocket(store.getWebSocketLocation());
  ws.onopen = (e) => {
    ws.send(JSON.stringify({
      action: "start",
      options: store.$state
    } as clientMessage));
    store.$subscribe((_, state)=>{
      ws.send(JSON.stringify({
        action: "update",
        options: state
      } as clientMessage));
    });
  }
  ws.onmessage = (e) => {
    const msg = serverMessageSchema.parse(JSON.parse(e.data));
    switch (msg.action) {
      case "start":
          streams.value.push(msg.name);
          break;
      case "end":
          streams.value.splice(streams.value.indexOf(msg.name), 1);
          break;
    }
  }
</script>


<template>
    <div :class="`grid auto-rows-fr grid-cols-${(streams.length == 1 ? 1 : 4 )} w-full gap-4 p-4 grow basis-3/4`">
      <Player v-for="stream in streams" :log-id="stream"/>
    </div>
</template>

// asciinema-dashboard/src/frontend/components/Grid.tsx
import Player from "./Player";
import { serverMessageSchema, type clientMessage } from "../../types";
import { extractPlayerValues, usePlayerStore } from "../store";
import { useState } from "react";
function Grid() {
  const [streams, setStreams] = useState<string[]>([]) 
  const store = usePlayerStore();
  const ws = new WebSocket(store.getWebSocketLocation());
  ws.onopen = () => {
    ws.send(JSON.stringify({
      action: "start",
      options: extractPlayerValues(store)
    } as clientMessage));
    usePlayerStore.subscribe((state)=>{
      ws.send(JSON.stringify({
        action: "update",
        options: extractPlayerValues(state)
      } as clientMessage));
    })
  }
  ws.onmessage = (e) => {
    const msg = serverMessageSchema.parse(JSON.parse(e.data));
    switch (msg.action) {
      case "start":
        setStreams(streams.concat([msg.name]))
        break;
      case "end":
        const index = streams.indexOf(msg.name)
        setStreams([...streams.slice(0, index), ...streams.slice(index + 1)])    
        break;
    }
  }
  return (
    <div className={`grid auto-rows-fr grid-cols-${(streams.length == 1 ? 1 : 4 )} w-full gap-4 p-4 grow basis-3/4`}>
    {streams.map((stream) => <Player logId={stream}/>)}
    </div>
  );
}

export default Grid;
