// asciinema-dashboard/src/frontend/components/Session.tsx
import { ArrowRightEndOnRectangleIcon, ArrowLeftStartOnRectangleIcon } from '@heroicons/react/24/solid';
import TOTP from './TOTP';
import { trpc } from '../utils';
import Popper from './Popover';

function Session() {
    const {data }= trpc.getUsername.useQuery()
    if (data) {
        return (
            <div v-if="data" className="flex flex-row p-2 gap-2">
                <TOTP/>
                <div>
                { data }
                </div>
                <Popper content="Log Out">
                    <a href="/auth/signout">
                        <ArrowLeftStartOnRectangleIcon className="h-6 w-6 cursor-pointer text-blue-500" />
                    </a>
                </Popper>
            </div>
        );
    } else {
        return (
            <Popper content="Log In">
                <a href="/auth/signin">
                    <ArrowRightEndOnRectangleIcon className="h-6 w-6 cursor-pointer text-blue-500" />
                </a>
            </Popper>
        );
    }
}
export default Session;

// asciinema-dashboard/frontend-backup/components/Session.vue
<script setup lang="ts">
import { ArrowRightEndOnRectangleIcon, ArrowLeftStartOnRectangleIcon } from '@heroicons/vue/24/solid';
import TOTP from './TOTP.vue';
import { trpc } from '../utils';
import { useQuery } from '@tanstack/vue-query';
    const { data, isError, error } = useQuery({
        queryKey: ['username'],
        queryFn: async () => trpc.getUsername.query(),
    })
</script>

<template>
    <div v-if="data" class="flex flex-row p-2 gap-2">
        <TOTP class="grow"/>
        <div>
            {{ data }}
        </div>
        <Popper offsetDistance="4" interactive="false" content="Log Out" hover>
            <a href="/auth/signout">
                <ArrowLeftStartOnRectangleIcon class="h-6 w-6 cursor-pointer text-blue-500" />
            </a>
        </Popper>
    </div>
    <Popper v-else content="Log In" offsetDistance="4" interactive="false" hover>
        <a href="/auth/signin">
            <ArrowRightEndOnRectangleIcon class="h-6 w-6 cursor-pointer text-blue-500" />
        </a>
    </Popper>
</template>
